PS C:\Users\richar.amadorl\Documents\AI_Engineer\LangChain\labgchainv0> & C:\Users\richar.amadorl\Documents\AI_Engineer\LangChain\labgchainv0\.venv\Scripts\python.exe c:/Users/richar.amadorl/Documents/AI_Engineer/LangChain/labgchainv0/langchain_v0.py
<sys>:0: UserWarning: Parameters {'seed'} should be specified explicitly. Instead they were passed in as part of `model_kwargs` parameter.
Traceback (most recent call last):
  File "c:\Users\richar.amadorl\Documents\AI_Engineer\LangChain\labgchainv0\langchain_v0.py", line 18, in <module>
    chat = ChatOpenAI(model_name = 'gpt-4',
                      model_kwargs = {'seed':365},
                      temperature = 0,
                      max_tokens = 100)
  File "C:\Users\richar.amadorl\Documents\AI_Engineer\LangChain\labgchainv0\.venv\Lib\site-packages\langchain_core\load\serializable.py", line 115, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\richar.amadorl\Documents\AI_Engineer\LangChain\labgchainv0\.venv\Lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "C:\Users\richar.amadorl\Documents\AI_Engineer\LangChain\labgchainv0\.venv\Lib\site-packages\langchain_openai\chat_models\base.py", line 793, in validate_environment
    self.root_client = openai.OpenAI(**client_params, **sync_specific)  # type: ignore[arg-type]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\richar.amadorl\Documents\AI_Engineer\LangChain\labgchainv0\.venv\Lib\site-packages\openai\_client.py", line 135, in __init__
    raise OpenAIError(
        "The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable"
    )
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable